artifact_uri: /home/tinkerspace/Desktop/Lane-Detection/runs/mlflow/353982981090875253/5b62c59de5e14596a57c9e9e3d99cea1/artifacts
end_time: null
entry_point_name: ''
experiment_id: '353982981090875253'
lifecycle_stage: active
run_id: 5b62c59de5e14596a57c9e9e3d99cea1
run_name: v1_highres
source_name: ''
source_type: 4
source_version: ''
start_time: 1772610025783
status: 1
tags: []
user_id: tinkerspace
