artifact_uri: /home/tinkerspace/Desktop/Lane-Detection/runs/mlflow/353982981090875253/02b56b23b40b40efb822e3623d41f091/artifacts
end_time: null
entry_point_name: ''
experiment_id: '353982981090875253'
lifecycle_stage: active
run_id: 02b56b23b40b40efb822e3623d41f091
run_name: v1_highres
source_name: ''
source_type: 4
source_version: ''
start_time: 1773050117318
status: 1
tags: []
user_id: tinkerspace
