artifact_location: /home/tinkerspace/Desktop/Lane-Detection/runs/mlflow/353982981090875253
creation_time: 1772530340473
experiment_id: '353982981090875253'
last_update_time: 1772530340473
lifecycle_stage: active
name: lane_project
workspace: default
