artifact_location: /home/tinkerspace/Desktop/Lane-Detection/runs/mlflow/0
creation_time: 1772530340433
experiment_id: '0'
last_update_time: 1772530340433
lifecycle_stage: active
name: Default
workspace: default
