artifact_uri: /home/tinkerspace/Desktop/Lane-Detection/runs/mlflow/353982981090875253/cd34975494ee4b37801820ee3a87e02d/artifacts
end_time: null
entry_point_name: ''
experiment_id: '353982981090875253'
lifecycle_stage: active
run_id: cd34975494ee4b37801820ee3a87e02d
run_name: v1_highres
source_name: ''
source_type: 4
source_version: ''
start_time: 1773050312325
status: 1
tags: []
user_id: tinkerspace
